### ISSUE TITLE
Description not sanitized causing some snippets to not load

### ISSUE THREAD

**Issue by Nexela** [Yokmp/atom-autocomplete-factorio#1]
Using Git Bash - mingw
Descriptions containing apostrophes cause the .cson to have errors. fix below

function clean_string($name, $switch = 'preg')
{
  switch ($switch) {
    case 'preg':
        $name = preg_replace( "/\s+/", "", $name );
        break;
    case 'str':
        $name = str_replace(array("\r", "\n"), '', $name);
        $name = str_replace("'", "\'", $name);
        break;
  }
  return $name;
}

**Comment by Yokmp** [comment]
Switched from coffee/cson to js/json and removed snippets. For now at least. And yes, I found that last night too. So its Fixed.
