### ISSUE TITLE
grep command not matching version string

### ISSUE THREAD

**Issue by Nexela** [Yokmp/atom-autocomplete-factorio#2]
in prepare.sh grep command wasn't matching the version
changing to this is working ok.
version="$(grep -o "Factorio [[:digit:]]_.[[:digit:]]_.[[:digit:]]*" $source)"

**Comment by Yokmp** [comment]
I use the current Version of Cygwin and here it works as expected. [[:digit:]] and .* should mean the same. There is technically a difference but it shouldn't matter in this case.

**Comment by Yokmp** [comment]
New update out!
Only uses PHP now which means the issue is 'solved'.
