### ISSUE TITLE
Missing a lot of functions

### ISSUE THREAD

**Issue by Nexela** [Yokmp/atom-autocomplete-factorio#3]
Right off the top it is missing a lot of functions. here is a small sample of what is missing.

game.remove_offline_players
entity.add_market_item
entity.remove_market_item

**Comment by Yokmp** [comment]
The script writes the Json from the Classes.html. 
The Methods you'd mentioned are also in there. I'll look into this.

**Comment by Yokmp** [comment]
Seems like I forgot to revert a change i made for testing. 
I've set the method-loop-count to a fixed value outside of the class-loop so it wasn't updating per class.

Besides that Fix it is now more verbose and creates a backupfile now. It's named 'api_$version.json' so you will have a backup if you ever want to change to an experimental build and back. Theoretically.
(To do this you have to change the URL in start.php at Line 23 and 30. Never tested that ;) )

**Comment by Nexela** [comment]
So far it looks good Thanks,  Also looks much better than the intial version :)
